### PR TITLE
Add xml comments to Linq methods

### PR DESCRIPTION
**Pull request by JohnEffo**
# What is this

Add XML documentation to Hedgehog.Linq so that C# consumers have a better experience.

### CODE REVIEW

**Comment by JohnEffo** [comment]
This nearly got added to #434 but did not make the cut, is there anything outstanding?

**Comment by TysonMN** [comment]
We haven't made that release yet.

@dharmaturtle reviewed this PR and gave feedback in a nonstandard way, namely PR https://github.com/JohnEffo/fsharp-hedgehog/pull/1 into your branch. We were waiting for you to review that PR.  We should have pointed this out.  Sorry for the confusion.

A minor issue I see is that this PR references your `master` branch while the PR by @dharmaturtle targets a different branch.  Not a big deal, but might be confusing if you don't notice that.

**Comment by dharmaturtle** [comment]
Ah whoops yeah I should've said something bout that PR here.

**Comment by JohnEffo** [comment]
Closing this PR as it is looking at my master branch, created #447 which supersedes this request

**Pull request closed without merging**
