### PR TITLE
Add property args structure.

### PR DESCRIPTION
**Pull request by adam-becker**
This PR adds a structure to keep all the run args in a single place. This will allow us to more easily add support for #25.

/cc @moodmosaic @TysonMN

### CODE REVIEW

**Comment by moodmosaic** [comment]
I think this looks good, however, perhaps we can merge once we're done with #296, unless @TysonMN has a better idea.

**Review by moodmosaic — COMMENTED** [review]
I think this looks good, however, perhaps we can merge once we're done with #296, unless @TysonMN has a better idea.

**Comment by adam-becker** [comment]
> I think this looks good, however, perhaps we can merge once we're done with #296, unless @TysonMN has a better idea.

That works for me 👍🏼

**Comment by TysonMN** [comment]
Also looks good to me.  I think we should merge now instead of waiting for #296.

**Pull request merged**
