### PR TITLE
Release 0.9.0

### PR DESCRIPTION
**Pull request by moodmosaic**
https://github.com/hedgehogqa/fsharp-hedgehog/compare/v0.8.4...47289c355040de7ff343a31780b2e1201ad5ab9e

/cc

@adam-becker
@cmeeren
@dharmaturtle
@mausch
@TysonMN

### CODE REVIEW

**Comment by cmeeren** [comment]
Will #252 be part of a later release, or will you wait with this release until that PR is merged?

**Comment by moodmosaic** [comment]
> Will #252 be part of a later release, or will you wait with this release until that PR is merged?

I'd like to look into https://github.com/hedgehogqa/fsharp-hedgehog/pull/252#issuecomment-746537111. But it may take several days to loo into it, and so I don't want to hold the release back.

**Comment by cmeeren** [comment]
I see. Please go ahead then.

**Comment by moodmosaic** [comment]
https://www.nuget.org/packages/Hedgehog/0.9.0

**Comment by cmeeren** [comment]
Great! I'll wait with releasing Hedgehog.Experimental until #252 is merged and released, since I want to use those new generators.

**Comment by moodmosaic** [comment]
Yep, or perhaps you can put those in Hedgehog.Experimental if you're in a hurry, and then we can move them here via #182.

**Comment by moodmosaic** [comment]
@adam-becker, @dharmaturtle, are you on Twitter? I can mention you in the v0.9.0 announcement, if you want. If so, please add your handles here please. :rocket: :unicorn: :guitar:

**Comment by dharmaturtle** [comment]
https://twitter.com/dharmaturtle though I never say anything interesting :)

**Comment by cmeeren** [comment]
> Yep, or perhaps you can put those in Hedgehog.Experimental if you're in a hurry, and then we can move them here via #182.

I'm in no hurry.

**Comment by TysonMN** [comment]
I did not expect the following breaking change.

Consider this test.  It passed with `Hedgehog` 0.8.4 and `Hedgehog.Experimental` 0.2.3.

```fsharp
module DiscriminatedUnionTests

open Xunit
open Hedgehog
open Swensen.Unquote

type Letters = A | B | C

[<Fact>]
let ``Default sorting order of DU cases matches defined order`` () =
  Property.check <| property {
    let expected = [ A; B; C ]
    let! input = expected |> GenX.shuffle

    let actual = input |> List.sort

    test <@ expected = actual @>
  }
```

With Hedgehog 0.9.0, that test fails.
```
  Message: 
    System.MissingMethodException : Method not found: 'System.Tuple`2<System.__Canon,Microsoft.FSharp.Core.FSharpFunc`2<Int32,System.Tuple`2<System.__Canon,System.__Canon>>> Hedgehog.Range`1.get_Item()'.
  Stack Trace: 
    shuffle@153-1.Invoke(Int32 _arg1)
    Delay@22.Invoke(Unit x)
    delay@18.Invoke(Seed seed, Int32 size)
    bindRandom@41.Invoke(Seed seed0, Int32 size)
    bindRandom@41.Invoke(Seed seed0, Int32 size)
    bindRandom@41.Invoke(Seed seed0, Int32 size)
    Property.loop@350-8(Boolean renderRecheck, Int32 n, Random`1 random, Seed seed, Int32 size, Int32 tests, Int32 discards)
    Property.Report(Int32 n, Property`1 p)
    Property.Check(Property`1 p)
    DiscriminatedUnionTests.Default sorting order of DU cases matches defined order() line 13
```

**Comment by dharmaturtle** [comment]
@TysonMN yeah I had this issue myself. I don't think you can mix `Hedgehog 0.9.0` with `Experimental 0.2.3`. Either drop `Experimental` or downgrade to `0.8.4`.

**Comment by TysonMN** [comment]
I don't mind continuing to use 0.8.4.  (I was excited to have support for `Property.check`!)  I just didn't expect that failure (and still don't understand why it is failing.

**Comment by dharmaturtle** [comment]
Yeah I'm just going off this [SO answer](https://stackoverflow.com/a/41824318).

Eventually, it might be nice to have the `Hedgehog` and `Hedgehog.Experimental` sync up their version numbers.

**Comment by moodmosaic** [comment]
I wonder if assembly binding redirection is still a thing...

**Comment by TysonMN** [comment]
It is.  I was depending directly on `Hedgehog` 0.9.0, so that is the version that gets loaded (because of the [Nearest Wins](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#nearest-wins) rule).  Any calls from `Hedgehog.Experimental` use that version even though version 0.2.3 was built and released against version 0.8.4 of `Hedgehog`.

**Comment by cmeeren** [comment]
The core of the problem seems to be binary compatibility (or rather, incompatibility). It can be a tricky thing to maintain, but if not done, then other packages that depend on it may break unless recompiled and re-released.

> Eventually, it might be nice to have the `Hedgehog` and `Hedgehog.Experimental` sync up their version numbers so users might be clued into why this is occuring.

Currently, that would cause a lot of unnecessary churn. We could pin the Hedgehog version in Hedgehog.Experimental, but that would require Hedgehog.Experimental updates for all Hedgehog updates, even when the new Hedgehog is binary compatible with the old one.

**Pull request merged**
