### PR TITLE
Fix up all references to the old location in Travis, NuGet, and README

### PR DESCRIPTION
**Pull request by moodmosaic**
See [comment](https://github.com/hedgehogqa/fsharp-hedgehog/issues/83#issuecomment-292697405) in #83.

### CODE REVIEW

**Comment by moodmosaic** [comment]
FWIW, I've just added 4d3e48c, which replaces the image we have on the README with the Hedgehog logo, without the hassle of doing this on a separate PR

**Comment by moodmosaic** [comment]
A preview of how it looks like is shown [here](https://github.com/moodmosaic/fsharp-hedgehog/blob/topic/fix-up-references/README.md).

**Comment by jystic** [comment]
The image doesn't seem like it is properly crisp? The edges are a bit soft, maybe it needs to be re-exported again or something? /not sure

**Comment by moodmosaic** [comment]
Yeah, I noticed that, but wasn't sure how to fix it. Should we get rid of the image entirely until we find out why it's happening? It looks fine in the mobile version though.
img_7641

**Comment by moodmosaic** [comment]
OK, I was able to fix it also on the desktop version, using HTML (as explained [here](http://stackoverflow.com/a/12118349/467754)) 🎉

capture

**Comment by jystic** [comment]
Maybe I'm crazy but I still think the edges on the logo / text look a bit soft, I'm going to merge this anyway to push the content through, but it would be good to fix it at some point.

The other [logos](https://github.com/hedgehogqa/haskell-hedgehog/blob/master/img/hedgehog-logo.png) you sent me by email look very sharp by comparison.

**Comment by moodmosaic** [comment]
That's weird. I made two versions, transparent and non-transparent. So I will try with the non-transparent one.

**Comment by moodmosaic** [comment]
Yes, I see what you mean now. It looks blurry on screens that have a higher pixel density (e.g. on my MacBook Pro). Looking at this.

**Comment by jystic** [comment]
Ah that must be what it is, I've been looking at it on a MacBook Pro also

If you look at the Haskell readme you can see I've set the width of the image tag to half the size of the actual image, that seems to work for retina displays.

**Comment by moodmosaic** [comment]
Yeah, I've fixed it, will open a PR in a few minutes 😃

**Comment by moodmosaic** [comment]
OK, I think it should be fixed if/after we merge #86.

This was the issue:

capture

So now I know that I suck *both* at writing READMEs and doing logos 😄

**Pull request merged**
