### PR TITLE
Add more detailed state for property.

### PR DESCRIPTION
**Pull request by adam-becker**
This PR aggregates all the "check time" state of a property into a single structure. This will hopefully make adding features like #341 easier, and I think it's much easier to see at a glance what's happening internally by looking at the new `PropertyState` module.

/cc @TysonMN @dharmaturtle

### CODE REVIEW

**Comment by TysonMN** [comment]
Can we merge #336 first? I don't want to fix merge conflicts.

**Comment by dharmaturtle** [comment]
I like this a lot.

**Comment by adam-becker** [comment]
> Can we merge #336 first? I don't want to fix merge conflicts.

Absolutely. Are we still waiting on a Fable issue there?

> I like this a lot.

:+1:

**Comment by TysonMN** [comment]
> > Can we merge #336 first? I don't want to fix merge conflicts.
> 
> Absolutely. Are we still waiting on a Fable issue there?

We are primarily waiting on PR #364 to be reviewed and completed.  After that, we could merge PR #336 with the understanding that the API needs some work, but maybe that is ok since improving the API around `Property` is what issue #365, PR #346, and this PR are intended to do.

**Pull request closed without merging**
