### PR TITLE
Fix Tree.render bug

### PR DESCRIPTION
**Pull request by TysonMN**
@moodmosaic, I just realized that you introduced a bug when you changed the implementation of `Tree.renderList` in PR #229.

This PR contains two commits.  The first commit increases the cases covered by the tests by changing the trees in the tests from full binary trees to full ternary trees.  The second commit reverts the implementation of `Tree.renderList` to how [my commit](https://github.com/hedgehogqa/fsharp-hedgehog/pull/229/commits/20d328df67e3def0a0e48b3875085e33237b0aca) computed the output.

In the second commit, I tried to keep all of your copy edits.  I am just trying to get back to an implementation that passes the tests.  Feel free to change it however you want again (but this time, try to not add a bug ;) :P ).

### CODE REVIEW

**Comment by moodmosaic** [comment]
Ouch! I apologize... That doesn't happen often. I should be more careful when editing.

**Comment by moodmosaic** [comment]
Since you're the author of the original implementation let's merge this and we can cleanup afterwards. I assume you'd have to reopen https://github.com/hedgehogqa/fsharp-hedgehog/issues/227.

**Comment by TysonMN** [comment]
No need to apologize.  It happens to all of us :)

I don't see an option to reopen #227.  Do you want it reopened?  I think keeping it closed it fine.

**Comment by moodmosaic** [comment]
Yep, since we quickly merged this one we can keep it closed. Thanks Tyson!

**Pull request merged**
