### PR TITLE
Add property documentation file, update links.

### LINKED ISSUE #270: Document all the report calls in Property module(s)
Especially with those added in https://github.com/hedgehogqa/fsharp-hedgehog/pull/269 many users can get lost as the API starts becoming bigger.

### PR DESCRIPTION
**Pull request by adam-becker**
fixes #270

I moved the documentation we had in the tutorial over to a new `property.md` file, and added a section about the reporting functions and how/why they might be useful, and included a brief example on how to use `Property.report`.

Since I believe this is the first PR to add documentation since #277 was merged, I am completely open to how we might want to structure our docs.

/cc @moodmosaic @TysonMN

### CODE REVIEW

**Review by moodmosaic — COMMENTED** [review]
Is there a link from the main docs page pointing at the property docs page? Looks fine other than that.

**Comment by adam-becker** [comment]
> Is there a link from the main docs page pointing at the property docs page? Looks fine other than that.

All of the markdown files under `doc` get a link on the sidebar when the files are built. You can try it out with a simple web server, I think python has one for this kind of thing.

**Comment by moodmosaic** [comment]
> > Is there a link from the main docs page pointing at the property docs page? Looks fine other than that.
> 
> All of the markdown files under `doc` get a link on the sidebar when the files are built. 

LGTM, then. 👍

**Comment by adam-becker** [comment]
@moodmosaic This is the last issue that is part of `0.10.0`, are you confident with snapping a release or is there more work to be done?

**Comment by moodmosaic** [comment]
It'd be great with a v0.10.0 release at this point. So many great stuff on master branch already.

The first thing we'd want is a release PR, similar to those other past ones. That should probably also kick off the NuGet Package automation.

I can do this release PR unless you'd want to try it @adam-becker. Just let me know. Happy to help either ways.

**Comment by adam-becker** [comment]
> It'd be great with a v0.10.0 release at this point. So many great stuff on master branch already.
> 
> The first thing we'd want is a release PR, similar to those other past ones. That should probably also kick off the NuGet Package automation.
> 
> I can do this release PR unless you'd want to try it @adam-becker. Just let me know. Happy to help either ways.
> 
> (Typing on a small keyboard, hence the brevity.)

If you don't mind doing the release and I can just observe, then in future releases I can take a stab at it. 😄

**Comment by adam-becker** [comment]
Just verified that the link shows up, I had seen it in the HTML, but wanted to be absolutely sure.

image

**Comment by moodmosaic** [comment]
> If you don't mind doing the release and I can just observe, then in future releases I can take a stab at it. 😄

Sure 👍

**Comment by moodmosaic** [comment]
> Just verified that the link shows up, I had seen it in the HTML, but wanted to be absolutely sure.

Looks good! In the future, perhaps, we can do the same also the Gen and Range.

**Comment by moodmosaic** [comment]
Thank you for doing this 👍

**Comment by adam-becker** [comment]
Gah, I forgot to update the TOC at the top of the file.

**Pull request merged**
