### PR TITLE
made Seq module internal and moved to own file

### LINKED ISSUE #306: Seq module scope
I would prefer if the `Seq` module had internal scope.  Currently it has public scope.

https://github.com/hedgehogqa/fsharp-hedgehog/blob/f346f77b40231978e6f7904b67f96b559780d548/src/Hedgehog/Shrink.fs#L3-L17

### PR DESCRIPTION
**Pull request by TysonMN**
Fixes #306

### CODE REVIEW

**Review by moodmosaic — APPROVED** [review]
LGTM /cc @adam-becker

**Comment by TysonMN** [comment]
...but not to the compiler 😩

**Comment by moodmosaic** [comment]
Remove the inline keyword, maybe?

**Comment by TysonMN** [comment]
I think understand now.

`Shrink.towards` is marked as inlined, so when that code is inlined in user code, then either `Seq.consNub` needs to be inlined as well or it needs to be accessible, which in this case is `public` scope.

**Comment by adam-becker** [comment]
LGTM 👍🏼

**Pull request merged**
